//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;




public class Gui extends JPanel {
    private JMenuBar jcomp1;
    private JTabbedPane Tabs = new JTabbedPane();
    private JTextArea txt1 = new JTextArea(10,10);




    public Gui() {

        //construct preComponents
        JMenu fileMenu = new JMenu ("File");
        JMenuItem printItem = new JMenuItem ("Print");
        fileMenu.add (printItem);
        JMenuItem exitItem = new JMenuItem ("Exit");
        fileMenu.add (exitItem);
        JMenu helpMenu = new JMenu ("Help");
        JMenuItem contentsItem = new JMenuItem ("Contents");
        helpMenu.add(contentsItem);
        JMenuItem aboutItem = new JMenuItem ("About");
        helpMenu.add(aboutItem);

        JComponent tab1;
        tab1 = new JComponent() {
            @Override
            public void setInheritsPopupMenu(boolean value) {
                super.setInheritsPopupMenu(value);
            }
        };
        JComponent tab2;
        tab2 = new JComponent() {
        };

        txt1.setBounds(50,50,20,20);


        tab2.add(txt1);

        JComponent tab3;
        tab3 = new JComponent() {
            @Override
            public void setInheritsPopupMenu(boolean value) {
                super.setInheritsPopupMenu(value);
            }
        };
        JComponent tab4;
        tab4 = new JComponent() {
            @Override
            public void setInheritsPopupMenu(boolean value) {
                super.setInheritsPopupMenu(value);
            }
        };
        JComponent tab5;
        tab5 = new JComponent() {
            @Override
            public void setInheritsPopupMenu(boolean value) {
                super.setInheritsPopupMenu(value);
            }
        };

        JTextArea tx1 = new JTextArea(10,10);
        tx1.setBounds(50,50,20,20);
        tx1.setVisible(true);


        Tabs.addTab("Tab1",tab1);
        Tabs.addTab("Tab2",tab2);
        Tabs.addTab("Tab3",tab3);
        Tabs.addTab("Tab4",tab4);
        Tabs.addTab("Tab5",tab5);



        //construct components
        jcomp1 = new JMenuBar();
        jcomp1.add (fileMenu);
        jcomp1.add (helpMenu);

        //add components
        add(jcomp1);
        add(Tabs);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds(0, 0, 796, 25);
        Tabs.setBounds(0, 25, 796, 25);
        //construct components

        //adjust size and set layout
        setPreferredSize(new Dimension (796, 566));
        setLayout (null);

        //add components

        //set component bounds (only needed by Absolute Positioning)
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Gui());
        frame.pack();
        frame.setVisible(true);
    }
}
