//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import sun.security.krb5.internal.PAEncTSEnc;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Tabbed_Gui extends JPanel {

    public Tabbed_Gui() {
        //construct components
        JTabbedPane tabs = new JTabbedPane();


        JPanel Panel1 = new JPanel();
        JPanel Panel2 = new JPanel();
        Panel1.setBounds(50,50,50,50);
        Panel2.setBounds(100,100,100,100);

        Panel1.setBackground(Color.black);
        Panel2.setBackground(Color.blue);


        tabs.addTab("One", Panel1);
        tabs.addTab("Two", Panel2);

        tabs.setBounds(0, 0, 800, 600);

        add(tabs);
     //   add(Panel1);
     //   add (Panel2);



        //adjust size and set layout
        setPreferredSize (new Dimension (800, 600));
        setLayout (null);

        //add components

        //set component bounds (only needed by Absolute Positioning)
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Tabbed_Gui());
        frame.pack();
        frame.setVisible (true);
    }
}
